save txt raw file
okfn-brasil/querido-diario-data-processing pull request #20
Opened 2021-04-25 14:56 UTC by andreformento

2021-04-29 12:44 UTC, jvanz requested changes
Thank you for this change! It is necessary for our first version. 

Can you add tests for the new function?

2021-04-29 12:44 UTC, jvanz commented on tasks/gazette_text_extraction.py
> +    file_raw_txt = f"{file_raw_txt}.txt"
I'm not sure if this is the better approach. There are more file types supported than only `pdf` and `doc`. I think you should use everything from the `file_path` until you find a dot (if it exists). Thus, we should be able to get the file name (the md5 of the file). Then, you can just add the `.txt` in the end. 

Another option to build the file key is using the "directory structure" you find in the `file_path` and concataneting with that the file md5 + the `.txt` extension.

2021-04-29 12:44 UTC, jvanz commented on storage/digital_ocean_spaces.py
> +        )
Cannot we use the same object used to download files to upload files?

2021-04-29 12:44 UTC, jvanz commented on tasks/gazette_text_extraction.py
> +def define_gazette_raw_text(
```suggestion
def upload_gazette_raw_text(
```

2021-04-29 12:44 UTC, jvanz commented on tasks/gazette_text_extraction.py
> +    define_gazette_raw_text(gazette, storage)
```suggestion
    upload_gazette_raw_text(gazette, storage)
```

2021-04-29 22:30 UTC, andreformento commented on storage/digital_ocean_spaces.py
> +        )
I don't know how to do this using `_client`. Can you help me do this using that, please? :eyes:

2021-05-02 12:44 UTC, andreformento commented on tasks/gazette_text_extraction.py
> +    file_raw_txt = f"{file_raw_txt}.txt"
I changed the method and now I'm trying to create the test, as you request. But for me the tests on the `main` branch are broken. I'm trying to fix `main` and after that I'm going to implementing this test.

Log error:
```
ERROR: test_extract_from_doc_file_should_return_text_file (tests.text_extraction_tests.ApacheTikaTextExtractorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1d9e7498b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /tika (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d9e7498b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/code/data_extraction/text_extraction.py", line 41, in extract_text
    return self._try_extract_text(filepath)
  File "/mnt/code/data_extraction/text_extraction.py", line 32, in _try_extract_text
    response = requests.put(f"{self._url}/tika", data=file, headers=headers)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /tika (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d9e7498b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/code/tests/text_extraction_tests.py", line 49, in test_extract_from_doc_file_should_return_text_file
    text = self.extractor.extract_text("tests/data/fake_gazette.doc")
  File "/mnt/code/data_extraction/text_extraction.py", line 43, in extract_text
    raise Exception("Could not extract file content") from e
Exception: Could not extract file content

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
make: *** [Makefile:101: retest] Error 1
```

2021-05-02 14:57 UTC, andreformento commented on tasks/gazette_text_extraction.py
> +    file_raw_txt = f"{file_raw_txt}.txt"
I saw just now! I fixed this in another [PR](https://github.com/okfn-brasil/querido-diario-data-processing/pull/19) :joy: 

I'm waiting for merge

2021-05-02 15:10 UTC, andreformento commented on tasks/gazette_text_extraction.py
> +    file_raw_txt = f"{file_raw_txt}.txt"
Tests done!
If you run on this branch `make test` (will fail), but if you run `make retest` will work!

This bug was resolved in other [PR](https://github.com/okfn-brasil/querido-diario-data-processing/pull/19)

2021-06-14 13:14 UTC, jvanz commented on storage/digital_ocean_spaces.py
> +        )
@andreformento can you do something similar when you have time? (I'm pinging you just to ensure that you noticed my last comment)

2021-06-15 11:12 UTC, jvanz requested changes
Marking PR as "Request changes" due the latest comments.

2021-06-25 22:44 UTC, andreformento commented on storage/digital_ocean_spaces.py
> +        )
@giuliocc helps me too. It's done :smile:

2021-06-26 12:06 UTC, andreformento commented on tests/text_extraction_task_tests.py
> -        self.storage_mock.upload_file.assert_not_called()
The method `upload_file` doesn't exists anywhere. Because of that, I removed

2021-06-28 20:10 UTC, jvanz reviewed
Let me run these changes locally.

2021-06-28 20:10 UTC, jvanz commented on tasks/gazette_text_extraction.py
> +    storage.upload_content(file_raw_txt, gazette["source_text"])
```suggestion
    storage.upload_content(file_raw_txt, gazette["source_text"])
    logging.debug(f"file_raw_txt uploaded {file_raw_txt}")
```

2021-07-03 17:39 UTC, jvanz requested changes
It runs fine in my enviroment. However, we need to fix the info stored in the index.

2021-07-03 17:39 UTC, jvanz commented on tasks/gazette_text_extraction.py
> +    gazette["file_raw_txt"] = file_raw_txt
You should build the whole URL like we do in `get_gazette_text_and_define_url`. Otherwise, we will store only the path in the DO spaces instead of the whole URL to the file as needed to the front-end.

2021-07-03 20:28 UTC, jvanz requested changes

2021-07-03 20:28 UTC, jvanz commented on tasks/gazette_text_extraction.py
> +    gazette["file_raw_txt"] = file_raw_txt
```suggestion
    file_endpoint = get_file_endpoint()
    gazette["file_raw_txt"] = f"{file_endpoint}/{file_raw_txt}"
```

2021-07-03 20:49 UTC, jvanz requested changes

2021-07-03 20:49 UTC, jvanz commented on tests/text_extraction_task_tests.py
> +        self.assertEqual(gazette["file_raw_txt"], "some_file.txt")
```suggestion
        self.assertEqual(gazette["file_raw_txt"], "http://test.com/some_file.txt")
```

2021-07-03 20:54 UTC, jvanz commented on tests/text_extraction_task_tests.py
> +                "file_raw_txt": "sc_gaspar/2020-10-18/972aca2e-1174-11eb-b2d5-a86daaca905e.txt",
```suggestion
                "file_raw_txt": "http://test.com/sc_gaspar/2020-10-18/972aca2e-1174-11eb-b2d5-a86daaca905e.txt",
```

2021-07-03 20:55 UTC, jvanz commented on tests/text_extraction_task_tests.py
> +                "file_raw_txt": "sc_gaspar/2020-10-18/972aca2e-1174-11eb-b2d5-a86daaca905e.txt",
```suggestion
                "file_raw_txt": "http://test.com/sc_gaspar/2020-10-18/972aca2e-1174-11eb-b2d5-a86daaca905e.txt",
```

2021-07-03 20:55 UTC, jvanz commented on tests/text_extraction_task_tests.py
> +                "file_raw_txt": "tests/data/fake_gazette.txt",
```suggestion
                "file_raw_txt": "http://test.com/tests/data/fake_gazette.txt",
```

2021-07-03 21:06 UTC, jvanz commented on tests/text_extraction_task_tests.py
> +                "file_raw_txt": "sc_gaspar/2020-10-18/972aca2e-1174-11eb-b2d5-a86daaca905e.txt",
```suggestion
                "file_raw_txt": "http://test.com/sc_gaspar/2020-10-18/972aca2e-1174-11eb-b2d5-a86daaca905e.txt",
```

2021-07-03 21:18 UTC, merged