Cria classe base para os segmentadores
okfn-brasil/querido-diario-data-processing pull request #53
Opened 2023-10-14 23:29 UTC by Jefersonalves

* Cria a classe base da qual os segmentadores devem herdar e implementar os métodos (#50)
* Transforma o segmentador da AMA em uma classe
* Cria o módulo `segmentation` para armazenar arquivos que lidam com a segmentação

2023-11-21 16:01 UTC, ogecece requested changes
@Jefersonalves tá aí o review! :raised_hands:

2023-11-22 00:13 UTC, Jefersonalves commented on segmentation/factory.py
> +def get_segmenter(association_spider_name: str, association_gazzete: dict[str, Any]) -> AssociationSegmenter:
Tem sim. Só trocar a chave do dicionário. A intenção é modificar essa parte do código para ficar compatível com as modificações do Luiz

2023-11-22 00:15 UTC, Jefersonalves commented on segmentation/base/association_segmenter.py
> +        return m.hexdigest()
Boa observação. Ele não pertence ao escopo da classe então melhor tratá-lo como uma função mesmo

2023-11-22 00:20 UTC, Jefersonalves commented on segmentation/factory.py
> +from segmentation.segmenters import ALAssociacaoMunicipiosSegmenter
Gostei mais da primeira opção, ficou mais limpo. Uma questão: Em ambas as sugestões ainda é preciso adicionar as chaves e os valores no dicionário segmenters, acha que vale a pena tentar construí-lo automaticamente?

2023-11-22 00:32 UTC, Jefersonalves commented on segmentation/segmenters/al_associacao_municipios.py
> +    def __init__(self, association_gazzete: dict[str, Any]):
Evitei mexer muito na estrutura do extrator do exoonero, ela não é muito flexível. Outro ponto é que ainda não temos testes para essa classe. Mas concordo que ela deve ser refatorada e acredito que o melhor momento para isso é após fecharmos os PRs da feature de segmentadores

2023-11-22 13:14 UTC, ogecece commented on segmentation/factory.py
> +from segmentation.segmenters import ALAssociacaoMunicipiosSegmenter
Acho que manter a declaração da associação explícita é melhor. Pode manter o dicionário

2023-11-22 23:44 UTC, Jefersonalves commented
@ogecece Concluí as modificações sugeridas na revisão. Por favor, veja se já podemos seguir com o merge

2023-11-23 18:26 UTC, ogecece commented
@Jefersonalves podemos sim.

Vi que passou a usar a `task.utils` e me fez pensar que depois precisaremos reorganizar esses diretórios, movê-los para um `src` da vida e subir um nível esse `utils`. Mas podemos fazer isso depois.

Pode só atualizar a branch com o que tem de novo na prototype e resolver o conflito?

2023-11-27 14:55 UTC, ogecece approved these changes

2023-11-27 15:16 UTC, merged