Implementação da funcionalidade de agregação de diários oficiais por ano e município/estado
okfn-brasil/querido-diario-data-processing pull request #78
Opened 2024-07-17 17:16 UTC by csafurtado

Implementação da rotina de agregação, responsável por fazer a extração dos conteúdos txt de todos os diários oficiais de um município em um período de um ano e transformá-lo em um arquivo XML para compactação em formato ZIP e disponibilização no sistema de arquivos. Também responsável por juntar todos os arquivos XML de todos os municípios de um determinado estado em um período de um ano para agregação e compactação em formato ZIP para disponibilização no sistema de arquivos.
Após as agregações e armazenagem dos arquivos ZIP, são disponibilizados meta dados dos arquivos no banco de dados para buscas otimizadas na API.

2024-07-18 21:38 UTC, ogecece reviewed
Subindo uma parte da revisão. Comecei a executar localmente, mas ainda não consegui analisar a task `gazette_txt_to_xml`.

2024-07-18 21:38 UTC, ogecece commented on storage/digital_ocean_spaces.py
> +        )
Seria melhor fazer uma verificação de tipo em `content_to_be_uploaded` no método `.upload_content()` e reutilizá-lo ao invés de criar um método novo só pra que um seja para `str` e o outro para `BytesIO`

2024-07-18 21:38 UTC, ogecece commented on storage/digital_ocean_spaces.py
> +        logging.debug(f"Deletando {file_key}")
Só pra seguir o padrão do projeto
```suggestion
        logging.debug(f"Deleting {file_key}")
```

2024-07-18 21:38 UTC, ogecece commented on tasks/interfaces.py
> +        Delete a file in the bucket S3.
```suggestion
        Delete a file on the host
```

2024-07-18 21:38 UTC, ogecece commented on tasks/utils/hash.py
> +    return hash_hex
Poderia ser uma função apenas `hash_content` verificando se o `content` é `str` ou `bytes` e transformando de acordo. O que acham?

2024-07-18 21:38 UTC, ogecece commented on tasks/utils/hash.py
> +    return hash_hex
Poderíamos usar `hashlib.sha256(content).hexdigest()`. O que acham?

2024-07-18 21:38 UTC, ogecece commented on tasks/utils/index.py
> +from tasks.interfaces import IndexInterface
O import relativo deu erro? Não entendi o motivo da mudança

2024-07-22 11:59 UTC, wildemberg-sales commented on storage/digital_ocean_spaces.py
> +        )
ok!

2024-07-22 11:59 UTC, wildemberg-sales commented on storage/digital_ocean_spaces.py
> +        logging.debug(f"Deletando {file_key}")
irei mudar

2024-07-22 11:59 UTC, wildemberg-sales commented on tasks/interfaces.py
> +        Delete a file in the bucket S3.
irei mudar

2024-07-22 11:59 UTC, wildemberg-sales commented on tasks/utils/hash.py
> +    return hash_hex
irei implementar

2024-07-22 12:01 UTC, wildemberg-sales commented on tasks/utils/hash.py
> +    return hash_hex
Você diz implementar isso na definição do algoritmo na linha 26, tornando redundante a linha 30. Correto?

2024-07-22 12:03 UTC, wildemberg-sales commented on tasks/utils/index.py
> +from tasks.interfaces import IndexInterface
Ela estava dando erro ao implementarmos outros módulos em sua pasta 'utils', verifiquei que ela estava fora do padrão e efetuei a correção

2024-07-22 19:47 UTC, ogecece commented on tasks/utils/hash.py
> +    return hash_hex
Digo para substituir o conteúdo da função toda, simplificando. Não vejo o `SEED_HASH` como necessário como não é uma função de segurança e esse seria a principal vantagem de usar a pbkdf2

2024-07-22 20:33 UTC, ogecece commented on tasks/utils/index.py
> +from tasks.interfaces import IndexInterface
É, como a task tá sendo executada diretamente como script, o caminho do utils fica incompleto pra poder funcionar o import relativo. Vou subir um commit aqui corrigindo esse comportamento. Seria muito complicado explicar o que precisa mudar

2024-07-22 22:11 UTC, ogecece requested changes

2024-07-22 22:11 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +                                            ORDER BY date ASC;"))
Acredito que meu ponto principal de revisão aqui será esse e ele deverá ter impacto em boa parte do código task então tô pensando em fazer ele, esperar as mudanças de vocês e depois atender outros detalhes.

A gente não precisa fazer tanta query (se tivéssemos 5570 municípios seriam 356k, hoje no banco de prod já seria por volta de 28k). E principalmente muita query que não dá resultado (todos os anos que não contém resultados). É mais interessante usar SQL a nosso favor.

Vou dar aqui um exemplo de query que pode ser feita e que facilita demais a lógica de `create_aggregates()` e `create_aggregates_for_territories_and_states()`:

```SQL
SELECT
    g.territory_id,
    t.state_code,
    date_part('Year', g.date) AS year,
    json_agg(g.*)  # colocando todos os campos por brevidade, mas preferencialmente deveríamos selecionar apenas os que serão usados por meio de json_build_object
FROM 
    gazettes g 
    LEFT JOIN 
        territories t 
    ON 
        g.territory_id = t.id 
GROUP BY 
    g.territory_id,
    t.state_code,
    year
```

Aqui já estamos agrupando por ano e território e o quarto campo do `SELECT` traz os resultados de `gazettes` já em formato de lista de dicionários.

Dessa forma, apenas uma query daria conta do banco todo. Mas diria que fatiar por município seria ideal pra não arriscar quebrar o banco com uma query com resultado gigantesco (que seria o banco todo):

```SQL
SELECT
    date_part('Year', g.date) AS year,
    json_agg(g.*)
FROM 
    gazettes g 
GROUP BY 
    year
WHERE
    g.territory_id = '9999999'
```

Assim, podemos reduzir o total de queries para no máximo 5571 com uma sendo a query inicial para sabermos quais municípios estão no banco e até 5570 por cada município no banco.

2024-07-22 22:51 UTC, ogecece requested changes
Colocando mais alguns pontos aqui antes de encerrar por hoje

2024-07-22 22:51 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +        ); """)
Isto poderia ser uma task isolada que seria executada antes de `create_aggregates`, criando a relação de dependência de recursos entre tasks

2024-07-22 22:51 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +def xml_content_generate(gazzetes_query_content:list, root, territory_id, storage):
Poderia usar a anotação de tipos como estamos fazendo em `gazette_text_extraction`?

2024-07-22 22:51 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +                path_arq_bucket = path_arq_bucket + ".txt"
Melhor usar a detecção e substituição de sufixo da [pathlib](https://docs.python.org/3/library/pathlib.html) do que essa verificação aqui que pode dar erro caso a extensão seja `.doc` ou até mesmo originalmente `.txt` (que ficaria `.txt.txt`)

2024-07-22 22:51 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +            continue
Esse erro é só para o `storage.get_file()`, certo? Duas coisas aqui: 

1. é bom evitar try-except tão abrangente (muitas linhas no `try`) quando possível, erros inesperados podem acontecer e acabarem passando despercebidos
2. na mesma linha do 1., precisamos separar erros esperados de inesperados e especificar o tipo de erro com `except ValueError` (ou até importar o erro exato de uma biblioteca de terceiros, como aqui seria um erro do `boto`)

2024-07-24 21:42 UTC, ogecece requested changes
Terminei essa fase da revisão. Não fiquei muito na `create_aggregates_for_territories_and_states` por conta do comentário anterior mas acho que as outras funções não vão mudar tanto então achei que valia complementar logo.

2024-07-24 21:42 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
Tornaria uma leitura mais natural se as funções mais externas tivessem em cima e as mais internas viessem abaixo. Ex: começar com `create_gazettes` e abaixo dela vir a primeira função que ela chama, e por aí vai.

2024-07-24 21:42 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +            need_update_zip_state = True
Penso que vale refatorar essa função `create_zip_for_territory()`, principalmente quanto às responsabilidades, ao uso da variável global e a verificação de necessidade de update. Mas acho que boa da solução vem de refatorar a `create_aggregates_for_territories_and_states()`, que chama ela.

Não vou entrar tanto na outra função, pois acho que ela ainda vai mudar bastante por conta do comentário anterior, mas vou delinear aqui por alto como acho que poderia ficar de uma forma que se parece com o código atual:

```python

def create_aggregates_for_territories_and_states(territories_list: List[Dict], state: str, database: DatabaseInterface, storage: StorageInterface):
    any_upsert_on_territory = False
    state_year_xmls = []
    for year in years:  # mantendo essa lógica aqui pois é assim que tá no código, mas pelo comentário que deixei anteriormente, acho que isso pode sumir
        for territory in territories:
            meta_xml = build_territory_xml(territory, year)  # toda a lógica de construção do xml
            meta_xml['hash_xml'] = hash_xml(meta_xml)
            state_year_xmls.append(meta_xml)
            
            needs_upsert = territory_zip_needs_upsert(meta_xml, database)  # verifica se o hash existe no banco
            if needs_upsert:
                any_update = True
                create_zip_for_territory_year(meta_xml, database, storage)

         if any_upsert_on_territory:
             create_zip_for_state(state_year_xmls, year, state, database, storage)
         
         any_upsert_on_territory = False
         state_year_xmls = []
```

Aqui tô colocando a lógica de upsert significando o insert ou update sendo necessários.

2024-07-24 21:42 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +                    %(hash_info)s, %(file_size)s);", dict_query_info)
Aqui daria pra usar uma lógica de [upsert](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/) (e no state tbm)

2024-07-24 21:42 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +    zip_path = f"aggregates/{state_code}/{state_code}-{year}.zip"
```suggestion
    zip_path = f"aggregates/{state_code}/{state_code}_{year}.zip"
```

2024-07-24 21:42 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +            zip_path = f"aggregates/{xml_file['state_code']}/{xml_file['territory_id']}-{xml_file['year']}.zip"
Está sendo usado em dois lugares e é idêntico. Poderia ser uma função a parte

2024-07-24 21:42 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +            zip_path = f"aggregates/{xml_file['state_code']}/{xml_file['territory_id']}-{xml_file['year']}.zip"
Seria melhor usar o nome do município junto ao territory_id. Fica mais fácil de organizar e de reconhecer o município. Sugiro o uso da util `get_territory_slug`.

```python
from .utils import get_territory_slug
...
            territory_slug = get_territory_slug({xml_file['territory_name'], xml_file['state_code']})
            zip_path = f"aggregates/{xml_file['state_code']}/{territory_slug}_{xml_file['territory_id']}_{xml_file['year']}.zip"
```

2024-08-07 17:08 UTC, csafurtado commented on storage/digital_ocean_spaces.py
> +        logging.debug(f"Deletando {file_key}")
Implementado!

2024-08-07 17:09 UTC, csafurtado commented on storage/digital_ocean_spaces.py
> +        )
Implementado!

2024-08-07 17:10 UTC, csafurtado commented on tasks/interfaces.py
> +        Delete a file in the bucket S3.
Implementado!

2024-08-07 17:10 UTC, csafurtado commented on tasks/utils/hash.py
> +    return hash_hex
Implementado!

2024-08-07 17:11 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +        ); """)
Implementado!

2024-08-07 17:11 UTC, csafurtado commented on tasks/utils/hash.py
> +    return hash_hex
Modificado!

2024-08-07 17:11 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +def xml_content_generate(gazzetes_query_content:list, root, territory_id, storage):
Implementado!

2024-08-07 17:12 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +                path_arq_bucket = path_arq_bucket + ".txt"
Modificado!

2024-08-07 17:12 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            continue
Colocada e especificada a exceção!

2024-08-07 17:13 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            meta_gazette = ET.SubElement(gazette_tag, "meta-gazette")
Implementado!

2024-08-07 17:13 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            ET.SubElement(gazette_tag, "conteudo").text = file_gazette_txt.getvalue().decode('utf-8')
Implementado!

2024-08-07 17:13 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +                ET.SubElement(meta_info_tag, "codigo_ibge", name="codigo_ibge").text = territories[0]
Implementado!

2024-08-07 17:14 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +                format_xml = minidom.parseString(xml_str).toprettyxml(indent=" ")
Implementado!

2024-08-07 17:14 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +                pass
Implementado!

2024-08-07 17:14 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +    print("========== Script que agrega os arquivos .txt para .xml de territórios e estados ==========")
Modificado colocando os logs!

2024-08-07 17:18 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +        xml_file.close()
Modificado!

2024-08-07 17:18 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            file_size REAL
Implementado!

2024-08-07 17:19 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
Modificado!

2024-08-07 17:19 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            need_update_zip_state = True
Modificação realizada através de uma função que faz essa verificação!

2024-08-07 17:19 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +                    %(hash_info)s, %(file_size)s);", dict_query_info)
Modificado!

2024-08-07 17:20 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +    zip_path = f"aggregates/{state_code}/{state_code}-{year}.zip"
Implementado!

2024-08-07 17:20 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            zip_path = f"aggregates/{xml_file['state_code']}/{xml_file['territory_id']}-{xml_file['year']}.zip"
Implementado!

2024-08-14 20:13 UTC, ogecece requested changes
Gente, tá excelente. Fiz a revisão tentando deixar o mais encaminhado possível. Daqui pra amanhã acho que já está pronto se vocês conseguirem pegar <3

2024-08-14 21:17 UTC, ogecece requested changes

2024-08-14 21:17 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +        meta_gazette = ET.SubElement(gazette_tag, "meta-diario")
Para manter a consistência com os outros campos
```suggestion
        meta_gazette = ET.SubElement(gazette_tag, "meta_diario")
```

2024-08-14 22:26 UTC, ogecece requested changes

2024-08-14 22:26 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +        "file_path": zip_path,
Notei que um problema que inicia aqui está estourando no frontend. Falta uma variável `file_url` onde temos a URL completa do arquivo para ser baixado. O frontend está puxando dessa variável `file_path` mas ele não tem informação sobre o endereço do bucket (nem deveria), então não consegue encontrar o arquivo para baixar.

2024-08-15 13:42 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +        "file_path": zip_path,
O endereço do bucket está sendo colocado pela própria API mesmo, através de uma variável de ambiente! Então o `file_path` é complementado na API e o front consegue encontrar o arquivo direitinho!

2024-08-15 14:27 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +        "file_path": zip_path,
Realmente não tinha notado aquela variável de ambiente, foi mal. Testei aqui e funcionou! Fechando esse comentário

2024-08-15 16:38 UTC, csafurtado commented on tasks/utils/hash.py
> +    logger.info(f"Hash: {result_hash}")
Implementado!

2024-08-15 16:38 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +need_update_zip_state = False
Retirado!

2024-08-15 16:39 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +    results_query_states = list(database.select(f"SELECT t.state_code AS code, json_agg(json_build_object('id',t.id, 'name',t.name)) FROM territories t GROUP BY code;"))
Query atualizada!

2024-08-15 16:39 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +
Query atualizada!

2024-08-15 16:40 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +        zip_file.writestr(f"{xml_file['territory_id']}-{xml_file['year']}.xml", xml_file['xml'])
Modificado!

2024-08-15 16:40 UTC, csafurtado commented on tasks/utils/need_upsert.py
> +    need_update = True
Modificado!

2024-08-15 16:40 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            xml_files_dict[year].append(meta_xml)
Modificado!

2024-08-15 16:40 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +            logger.error(f"Erro na obtenção do conteúdo de texto do diário do territorio {gazette['territory_id']}: {e}")
Modificado!

2024-08-15 16:41 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +        meta_gazette = ET.SubElement(gazette_tag, "meta-diario")
Atualizado!

2024-08-15 16:41 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +                zip_file.writestr(f"{xml_file['territory_id']}-{xml_file['year']}.xml", xml_file['xml'])
Modificado!

2024-08-15 17:57 UTC, ogecece commented on tasks/utils/hash.py
> +    logger.info(f"Hash: {result_hash}")
Pode remover o import e o logger não usados @csafurtado ?

2024-08-15 18:59 UTC, csafurtado commented on tasks/utils/hash.py
> +    logger.info(f"Hash: {result_hash}")
Removido!

2024-08-15 19:05 UTC, ogecece commented on tasks/gazette_txt_to_xml.py
> +        zip_file.writestr(f"{xml_file['territory_id']}-{xml_file['year']}.xml", xml_file['xml'])
Ficou faltando alterar o log aqui

2024-08-15 21:16 UTC, csafurtado commented on tasks/gazette_txt_to_xml.py
> +        zip_file.writestr(f"{xml_file['territory_id']}-{xml_file['year']}.xml", xml_file['xml'])
Log alterado!

2024-08-15 21:54 UTC, ogecece approved these changes

2024-08-15 21:56 UTC, ogecece commented
Gente, testei aqui. APROVADO!

Podem fazer aquele ajuste nos commits?

2024-08-16 13:23 UTC, merged